### ISSUE TITLE
docker-compose is not working

### ISSUE THREAD

**Issue by VadimGush** [gush-labs/kazan#29]
`docker-compose` is not working because `vite` is missing. It should be installed in our Docker image.

**Comment by harsh8051** [comment]
Hi Vadim (Sorry if its not your name as per first name policy)
Will you please specify On which OS you are working ?
and is error in your terminal like this
```
Creating kazan_kazan_1 ... done
Attaching to kazan_kazan_1
kazan_1  | 
kazan_1  | > hiragana@0.0.0 dev
kazan_1  | > vite
kazan_1  | 
kazan_1  | /tmp/dev-dbdefc0e.sh: 1: vite: not found


```

**Comment by VadimGush** [comment]
@harsh8051 Yep, exactly like this. I on MacOS with ARM M1 chip.
I just tried to run `docker-compose` on newly cloned repository and this is the exact error that I've got.

**Comment by harsh8051** [comment]
Thank you @bill876  for binding port

I have observed one thing as you mentioned when repository is newly cloned it gives that error but when I install *node_modules* on host machine/ locally and then try to `docker-compose up` it works

I have attached my console output of each step with comment 
[report.txt](https://github.com/gush-labs/kazan/files/9433202/report.txt)

If same scene is on your machine like **Vite works in docker only when it is working on host machine** then I will finalize it as Problem Statement and going to start work on it

**Comment by VadimGush** [comment]
@harsh8051 Because this docker setup is intended for new contributors who don't have anything installed locally (npm for example to run `npm install`), I believe this issue should be fixed. Thank you in advance.

For me this doesn't work even in case if I run `npm install` on my host machine, because node modules for Darwin (MacOS) are incompatible with Debian which is used as a base for `node` docker image. But this is just how it is. So it's not an issue.

**Comment by bill876** [comment]
Basically the "right" solution depends on what you @VadimGush want to use docker for.
If it's "to let someone quickly check something without installing node" then let's just remove the `.` bind mount and call it a day. Yes, the downside is that code changes will not be reflected in real time inside the container, so no hot reloading will occur and to see changes you'll have to rebuild, e.g. using `docker compose up --build`

Other options have other (worse, imo) downsides. And if the change is not a small one, I'm not buying this "quickly check", installing node is not a big price to make changes to a js project. I'd rather make a doc on how to do that than maintain workarounds for docker.

<details>
<summary>Researched alternatives</summary>

===
```
WORKDIR /usr/kazan
COPY package*.json ./
RUN npm ci
ENV NODE_PATH=/usr/kazan/node_modules

WORKDIR /usr/kazan/app
COPY . .
```
Install `node_modules` inside the container into a separate directory outside of the app work dir. This will separate the host node_modules and container node_modules almost completely. "Almost", because some packages may hardcode `./node_modules` as their working dir. And when they write there, changes will be reflected on the host filesystem.

And when something writes to a bound directory we have a new type of issue, that owner user and group on the host will have the same id as in the container. Basically this means that if your host uid or gid is not 1000, your user won't be the owner of those created files. To change that we would have to add support-- and you-the-new-contributor would have to set some environment variables before building images or starting containers. 
So the setup will have more to it than just `docker compose up`. 

This does not fit into an easy new contributor experience. Installing node would be not harder. Moreover, this will increase the maintaining effort for a not-very-useful imo result.


===
```
  kazan:
    build: .
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules/
```

Use a docker volume for node_modules that are inside the container. 
This would separate node_modules content completely.
The downsides:
* The volume will not be deleted when you stop a container (or even `down`). So when dependencies change, you'll have to either manually install them from inside a running container or delete the volume and restart. It may be easy, but completely not obvious.
* If you start a container when you have no node_modules on the host, docker engine will create it as an empty dir, and it will have the `root:root` owner (because this is the user that you run the docker engine as). So in a case where you "quickly check something" and afterwards decide to `npm i` on the host, it will fail with a permission error, until you `sudo rm -rf node_modules`. 

This, again, doesn't fit into an easy new contributor experience.
</details>

**Comment by VadimGush** [comment]
@bill876 Let's just remove `.` bind by now, and deal with that later.

**Comment by bill876** [comment]
Done
Not sure if you want to close this issue or keep it

**Comment by VadimGush** [comment]
@bill876 Thanks, I will close this issue after problem with `vite` missing will be resolved.

**Comment by bill876** [comment]
@VadimGush it should be now

**Comment by VadimGush** [comment]
@bill876 @harsh8051 Everything works! I'm closing this issue.
<img width="1028" alt="Screenshot 2022-08-27 at 03 23 17" src="https://user-images.githubusercontent.com/6123702/187002371-6c144607-fbbe-4d72-a8ec-be1123b577a4.png">
